name: "Deploy NuGet Package"

on:
  push:
    branches: ["main"]

env:
  PROJECT_PATH: "Test.Niculici/Test.Niculici.csproj"
  PACKAGE_OUTPUT_DIRECTORY: "${{ github.workspace }}/output"
  NUGET_SOURCE_URL: ""

jobs:
  deploy:
    name: "Deploy"
    runs-on: "self-hosted"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        
      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: '8.0.x'
          
      - name: "Build porject"
        run: "dotnet build ${{ env.PROJECT_PATH }} --configuration Release"

      - name: "Pack project"
        run: "dotnet pack ${{ env.PROJECT_PATH }} --no-build --configuration Release --include-symbols -p:PackageVersion=1.0.0 --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}"

      - name: "Push package"
        run: "dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ secrets.NUGET_AUTH_TOKEN }}"
