name: "Deploy NuGet Package"

on:
  push:
    branches: ["main"]

env:
  PROJECT_PATH: "Test.Niculici/Test.Niculici.csproj"
  PACKAGE_OUTPUT_DIRECTORY: "${{ github.workspace }}/output"
  NUGET_SOURCE_URL: "https://nuget.pkg.github.com/niculicicris/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: "self-hosted"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
          
      - name: "Build project"
        run: "dotnet build ${{ env.PROJECT_PATH }} --configuration Release"

      - name: "Pack project"
        run: "dotnet pack ${{ env.PROJECT_PATH }} --no-build --configuration Release -p:PackageVersion=1.0.0 --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}"

      - name: "Push package"
        run: "dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --skip-duplicate -s ${{ env.NUGET_SOURCE_URL }} -k ${{ secrets.NUGET_AUTH_TOKEN }}"
